version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Sol Lewitt"
description: "Sol Lewitt interactive project"
url: "http://behrooz-tahanzadeh.github.io/sol-lewitt/"
date: "Jan 2016"
googleAnalyticsCode: "UA-40560087-5"
